### ISSUE TITLE
Crash sometime if teleported from radio block

### ISSUE THREAD

**Issue by XenonRaite** [PC-Logix/OpenFM#30]
java.lang.NullPointerException: Unexpected error
+ 	at pcl.OpenFM.player.AdvancedPlayer.createEvent(AdvancedPlayer.java:185)
+ 	at pcl.OpenFM.player.AdvancedPlayer.createEvent(AdvancedPlayer.java:181)
+ 	at pcl.OpenFM.player.AdvancedPlayer.stop(AdvancedPlayer.java:197)
+ 	at pcl.OpenFM.player.PlayerDispatcher.stop(PlayerDispatcher.java:82)
+ 	at pcl.OpenFM.OpenFM.killAllStreams(OpenFM.java:99)
+ 	at pcl.OpenFM.Handler.ClientEvent.worldUnload(ClientEvent.java:16)
+ 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_996_ClientEvent_worldUnload_Unload.invoke(.dynamic)
+ 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
+ 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
+ 	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2153)
+ 	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
+ 	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:874)
+ 	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32)
+ 	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13)
+ 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
+ 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
+ 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
+ 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
+ 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
+ 	at net.minecraft.client.main.Main.main(SourceFile:148)
+ 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
+ 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
+ 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
+ 	at java.lang.reflect.Method.invoke(Unknown Source)
+ 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
+ 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by XenonRaite** [comment]
thx!
