### ISSUE TITLE
setURL(), start(), stop() not works

### ISSUE THREAD

**Issue by IgorTimofeev** [PC-Logix/OpenFM#34]
We have several servers designed for young programmers - and on every server with different modpacks does not work any method, except for the volume changing. For example, if I use Lua-methods .setURL() or .start() or .stop(), nothing happens on radio GUI and the server gives the following error:

P.S. All URLs are correct and works properly if I paste them through radio GUI.

```
[17:19:06] [OpenComputers-Computer-4/WARN]: java.lang.IllegalArgumentException: unexpected url: 
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at com.squareup.okhttp.Request$Builder.url(Request.java:163)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at pcl.OpenFM.TileEntity.TileEntityRadio.startStream(TileEntityRadio.java:115)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at pcl.OpenFM.TileEntity.TileEntityRadio.callMethod(TileEntityRadio.java:568)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at pcl.OpenFM.TileEntity.TileEntityRadio.invoke(TileEntityRadio.java:657)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.machine.Callbacks$PeripheralCallback.apply(Callbacks.scala:132)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.network.Component$class.invoke(Component.scala:113)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.invoke(Network.scala:599)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.network.Component$class.invoke(Component.scala:20)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.invoke(Network.scala:599)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.machine.Machine.invoke(Machine.scala:336)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.invoke(NativeLuaArchitecture.scala:55)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:78)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:74)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:24)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.repack.com.naef.jnlua.LuaState.lua_resume(Native Method)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.repack.com.naef.jnlua.LuaState.resume(LuaState.java:1754)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.runThreaded(NativeLuaArchitecture.scala:231)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at li.cil.oc.server.machine.Machine.run(Machine.scala:893)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:19:06] [OpenComputers-Computer-4/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:19:13] [Server thread/INFO]: ECS lost connection: Disconnected
[17:19:13] [Server thread/INFO]: ECS left the game.
```

**Comment by CaitlynMainer** [comment]
I can't reproduce this, what version of OpenComputers, and OpenFM are you on?

**Comment by IgorTimofeev** [comment]
OpenComputers-MC1.7.10-1.5.21.41-universal
OpenFM-1.7.10-0.1.0-29.jar (any version since OpenFM-0.1.0-20.jar doesn't works with setURL() method)

**Comment by axelpx** [comment]
OpenComputers-MC1.7.10-1.5.22.46-universal
OpenFM-1.7.10-0.1.0-29

**Comment by melekaiah** [comment]
I cant get this running either. same version as axelpx

**Comment by IgorTimofeev** [comment]
Come on, brother-developer, come on! We need to fix your wonderful mod. Just look what programm is waiting for a fix :D

![2016-03-04_14 41 28](https://cloud.githubusercontent.com/assets/11760002/13796313/22c4120e-eb17-11e5-9032-0c0909de63a0.png)

**Comment by CaitlynMainer** [comment]
@IgorTimofeev  any chance of you sharing that radio control script?

**Comment by IgorTimofeev** [comment]
@CaitlynMainer Everything works fine, thanks! .setURL() sets correct, but i've founded new issue, here: https://github.com/PC-Logix/OpenFM/issues/36

And radio control script is a part of my MineOS, you can install it using command:
`pastebin run 0nm5b1ju`

But it's not translated to English, sorry :)
