### ISSUE TITLE
1.9.4-0.1.0.7 Doesn't Play

### ISSUE THREAD

**Issue by kreezxil** [PC-Logix/OpenFM#43]
When I try to play a stream nothing happens.

In the client console the following exists:

```
Jul 20, 2016 5:49:55 PM io.netty.channel.embedded.EmbeddedChannel recordException
WARNING: More than one exception was raised. Will report only the first one and log others.
java.lang.NullPointerException
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:212)
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:263)
	at pcl.OpenFM.TileEntity.TileEntityRadio.func_189517_E_(TileEntityRadio.java:411)
	at pcl.OpenFM.TileEntity.TileEntityRadio.addStation(TileEntityRadio.java:288)
	at pcl.OpenFM.GUI.GuiRadio.actionPerformed(GuiRadio.java:338)
	at pcl.OpenFM.GUI.GuiRadioBase.func_73864_a(GuiRadioBase.java:122)
	at pcl.OpenFM.GUI.GuiRadio.func_73864_a(GuiRadio.java:381)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:546)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:515)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by CaitlynMainer** [comment]
MC 1.9.4 or 1.10.2?  Also I need the stream URL.

**Comment by CaitlynMainer** [comment]
I can't confirm this in 1.9.4-0.1.0.8 on 1.10.2 or 1.9.4
