### ISSUE TITLE
OpenFM (1.7.10) crash

### ISSUE THREAD

**Issue by Sirse** [PC-Logix/OpenFM#61]
SHIFT-click on radio GUI slot causes crash:

java.lang.IndexOutOfBoundsException: Index: 36, Size: 10
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75135_a(SourceFile:427)
	at pcl.OpenFM.TileEntity.RadioContainer.func_82846_b(RadioContainer.java:68)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at pcl.OpenFM.GUI.GuiRadioBase.func_73864_a(GuiRadioBase.java:123)
	at pcl.OpenFM.GUI.GuiRadio.func_73864_a(GuiRadio.java:377)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at launcher.lOlkEKchebureK.LoLkeKChEbUREk(Unknown Source)
	at launcher.lOlkEKchebureK.main(Unknown Source)

**Comment by CaitlynMainer** [comment]
What where you trying to shift-click from? Index 36 is way out of the range of slots that should be visible from the Radio GUI.

**Comment by Sirse** [comment]
Just click on first slot (in OpenFM gui, mirrored from hotbar).

**Comment by CaitlynMainer** [comment]
I've still yet to get a chance to reproduce this, I've not forgot about it though.

**Comment by MaxBas** [comment]
I have the same error but with a index of 10.
What can i do that the bug doesnt appear, because if you can reproduce the bug, there need to be a way that the game dont have throw this bug
