### ISSUE TITLE
OpenComputers API

### ISSUE THREAD

**Issue by veso266** [PC-Logix/OpenFM#63]
Hi I discovered that there are some extra commands with OC API like:
`getAttachedSpeakerCount()`
`getAttachedSpeakers()`
`getListenRedstone()`
`getScreenColor()`
`getVol()`
`greet()  what does this do it returns some dante line: Lasciate ogne speranza, voi ch'intrate # abandon all hope, ye who enter` # https://www.merriam-webster.com/dictionary/lasciate%20ogni%20speranza,%20voi%20ch'entrate 
`isPlaying()`
`play()`
`setListenRedstone()`

and I would love to `getScreenText()` 

also I can't `setScreenText()`
when I do `=setScreenText("something") I got "[cannot be cast to java.lang.String"`
and when I want to set something on screen with `fm.setScreenText("Example")` nothing is set on Radio Screen although `setScreenColor(255)` works fine

Thanks for Anwsering and Best Regards
BTW: I am using the latest OpenFM and latest OpenComputers on Minecraft 1.7.10

PS: that what I get in log when I try to `fm.setScreenText("Radio")`
`[B#349]  WARNING: More than one exception was raised. Will report only the first one and log others.
[B#349]  io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[B#349]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[B#349]  	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
[B#349]  	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
[B#349]  	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
[B#349]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
[B#349]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
[B#349]  	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
[B#349]  	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
[B#349]  	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210)
[B#349]  	at pcl.OpenFM.TileEntity.TileEntityRadio.func_145844_m(TileEntityRadio.java:393)
[B#349]  	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
[B#349]  	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533)
[B#349]  	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
[B#349]  	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)
[B#349]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
[B#349]  	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[B#349]  	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[B#349]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[B#349]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[B#349]  Caused by: java.lang.NullPointerException
[B#349]  	at pcl.OpenFM.network.Message.MessageTERadioBlock.toBytes(MessageTERadioBlock.java:151)
[B#349]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:11)
[B#349]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:7)
[B#349]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51)
[B#349]  	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
[B#349]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
[B#349]  	... 18 more
[B#349]
`
and it doesn't stop it just spawns console with it until I close Minecraft

**Comment by CaitlynMainer** [comment]
Please check and see if this is working properly now.

**Comment by veso266** [comment]
Sorry for late replay but it is still the same the onlything I did was updated OpenFM and OpenComputers to their latest versions

I tried =fm.setScreenText("Radio") and it complaint that it cannot cast it into string so I tried fm.setScreenText(Radio) and didn't do anything and spawned the console with 

```
[B#360]  [20:51:27] [Server thread/INFO] [openfm]: Stopping all currently running radio streams.
[B#360]  [20:51:27] [Server thread/INFO] [STDOUT]: [eu.thesociety.DragonbornSR.DragonsRadioMod.Handler.Cmsg:writeline:12]: [Dragon's Radio Mod] Stopping all currently running radio streams.
[B#360]  [20:51:27] [Server thread/INFO] [FML]: Unloading dimension 1
[B#360]  [20:51:34] [OpenComputers-Computer-1/ERROR] [FML]: FMLIndexedMessageCodec exception caught
[B#360]  io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[B#360]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
[B#360]  	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210) [SimpleNetworkWrapper.class:?]
[B#360]  	at pcl.OpenFM.TileEntity.TileEntityRadio.func_145844_m(TileEntityRadio.java:334) [TileEntityRadio.class:?]
[B#360]  	at pcl.OpenFM.TileEntity.TileEntityRadio.callMethod(TileEntityRadio.java:539) [TileEntityRadio.class:?]
[B#360]  	at pcl.OpenFM.TileEntity.TileEntityRadio.invoke(TileEntityRadio.java:624) [TileEntityRadio.class:?]
[B#360]  	at li.cil.oc.server.machine.Callbacks$PeripheralCallback.apply(Callbacks.scala:129) [Callbacks$PeripheralCallback.class:?]
[B#360]  	at li.cil.oc.server.network.Component$class.invoke(Component.scala:113) [Component$class.class:?]
[B#360]  	at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.invoke(Network.scala:629) [Network$ComponentBuilder$$anon$2.class:?]
[B#360]  	at li.cil.oc.server.machine.Machine.invoke(Machine.scala:358) [Machine.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.invoke(NativeLuaArchitecture.scala:55) [NativeLuaArchitecture.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:74) [ComponentAPI$$anonfun$initialize$5.class:?]
[B#360]  	at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:24) [ExtendedLuaState$ExtendedLuaState$$anon$1.class:?]
[B#360]  	at li.cil.repack.com.naef.jnlua.LuaState.lua_resume(Native Method) [LuaState.class:?]
[B#360]  	at li.cil.repack.com.naef.jnlua.LuaState.resume(LuaState.java:1758) [LuaState.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.runThreaded(NativeLuaArchitecture.scala:228) [NativeLuaArchitecture.class:?]
[B#360]  	at li.cil.oc.server.machine.Machine.run(Machine.scala:948) [Machine.class:?]
[B#360]  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[B#360]  Caused by: java.lang.NullPointerException
[B#360]  	at cpw.mods.fml.common.network.ByteBufUtils.writeUTF8String(ByteBufUtils.java:132) ~[ByteBufUtils.class:?]
[B#360]  	at pcl.OpenFM.network.message.MessageRadioSync.toBytes(MessageRadioSync.java:58) ~[MessageRadioSync.class:?]
[B#360]  	at pcl.OpenFM.network.MessageRadioBase.toBytes(MessageRadioBase.java:48) ~[MessageRadioBase.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:11) ~[SimpleIndexedCodec.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
[B#360]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[MessageToMessageEncoder.class:?]
[B#360]  	... 32 more
[B#360]  [20:51:34] [OpenComputers-Computer-1/ERROR] [FML]: SimpleChannelHandlerWrapper exception
[B#360]  io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[B#360]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
[B#360]  	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210) [SimpleNetworkWrapper.class:?]
[B#360]  	at pcl.OpenFM.TileEntity.TileEntityRadio.func_145844_m(TileEntityRadio.java:334) [TileEntityRadio.class:?]
[B#360]  	at pcl.OpenFM.TileEntity.TileEntityRadio.callMethod(TileEntityRadio.java:539) [TileEntityRadio.class:?]
[B#360]  	at pcl.OpenFM.TileEntity.TileEntityRadio.invoke(TileEntityRadio.java:624) [TileEntityRadio.class:?]
[B#360]  	at li.cil.oc.server.machine.Callbacks$PeripheralCallback.apply(Callbacks.scala:129) [Callbacks$PeripheralCallback.class:?]
[B#360]  	at li.cil.oc.server.network.Component$class.invoke(Component.scala:113) [Component$class.class:?]
[B#360]  	at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.invoke(Network.scala:629) [Network$ComponentBuilder$$anon$2.class:?]
[B#360]  	at li.cil.oc.server.machine.Machine.invoke(Machine.scala:358) [Machine.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.invoke(NativeLuaArchitecture.scala:55) [NativeLuaArchitecture.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:74) [ComponentAPI$$anonfun$initialize$5.class:?]
[B#360]  	at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:24) [ExtendedLuaState$ExtendedLuaState$$anon$1.class:?]
[B#360]  	at li.cil.repack.com.naef.jnlua.LuaState.lua_resume(Native Method) [LuaState.class:?]
[B#360]  	at li.cil.repack.com.naef.jnlua.LuaState.resume(LuaState.java:1758) [LuaState.class:?]
[B#360]  	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.runThreaded(NativeLuaArchitecture.scala:228) [NativeLuaArchitecture.class:?]
[B#360]  	at li.cil.oc.server.machine.Machine.run(Machine.scala:948) [Machine.class:?]
[B#360]  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_91]
[B#360]  	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[B#360]  Caused by: java.lang.NullPointerException
[B#360]  	at cpw.mods.fml.common.network.ByteBufUtils.writeUTF8String(ByteBufUtils.java:132) ~[ByteBufUtils.class:?]
[B#360]  	at pcl.OpenFM.network.message.MessageRadioSync.toBytes(MessageRadioSync.java:58) ~[MessageRadioSync.class:?]
[B#360]  	at pcl.OpenFM.network.MessageRadioBase.toBytes(MessageRadioBase.java:48) ~[MessageRadioBase.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:11) ~[SimpleIndexedCodec.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
[B#360]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[MessageToMessageEncoder.class:?]
[B#360]  	... 32 more
[B#360]  [20:51:34] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
[B#360]  io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[B#360]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
[B#360]  	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210) [SimpleNetworkWrapper.class:?]
[B#360]  	at pcl.OpenFM.TileEntity.TileEntityRadio.func_145844_m(TileEntityRadio.java:334) [TileEntityRadio.class:?]
[B#360]  	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591) [mr.class:?]
[B#360]  	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533) [mr.class:?]
[B#360]  	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67) [mq.class:?]
[B#360]  	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185) [mt.class:?]
[B#360]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
[B#360]  	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[B#360]  	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
[B#360]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[B#360]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#360]  Caused by: java.lang.NullPointerException
[B#360]  	at cpw.mods.fml.common.network.ByteBufUtils.writeUTF8String(ByteBufUtils.java:132) ~[ByteBufUtils.class:?]
[B#360]  	at pcl.OpenFM.network.message.MessageRadioSync.toBytes(MessageRadioSync.java:58) ~[MessageRadioSync.class:?]
[B#360]  	at pcl.OpenFM.network.MessageRadioBase.toBytes(MessageRadioBase.java:48) ~[MessageRadioBase.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:11) ~[SimpleIndexedCodec.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
[B#360]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[MessageToMessageEncoder.class:?]
[B#360]  	... 18 more
[B#360]  [20:51:34] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
[B#360]  io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[B#360]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
[B#360]  	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
[B#360]  	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210) [SimpleNetworkWrapper.class:?]
[B#360]  	at pcl.OpenFM.TileEntity.TileEntityRadio.func_145844_m(TileEntityRadio.java:334) [TileEntityRadio.class:?]
[B#360]  	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591) [mr.class:?]
[B#360]  	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533) [mr.class:?]
[B#360]  	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67) [mq.class:?]
[B#360]  	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185) [mt.class:?]
[B#360]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
[B#360]  	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[B#360]  	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
[B#360]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[B#360]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#360]  Caused by: java.lang.NullPointerException
[B#360]  	at cpw.mods.fml.common.network.ByteBufUtils.writeUTF8String(ByteBufUtils.java:132) ~[ByteBufUtils.class:?]
[B#360]  	at pcl.OpenFM.network.message.MessageRadioSync.toBytes(MessageRadioSync.java:58) ~[MessageRadioSync.class:?]
[B#360]  	at pcl.OpenFM.network.MessageRadioBase.toBytes(MessageRadioBase.java:48) ~[MessageRadioBase.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:11) ~[SimpleIndexedCodec.class:?]
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
[B#360]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51) ~[FMLIndexedMessageToMessageCodec.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
[B#360]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[MessageToMessageEncoder.class:?]
[B#360]  	... 18 more
[B#360]  avg. 10, 2018 8:51:34 PM io.netty.channel.embedded.EmbeddedChannel recordException
[B#360]  WARNING: More than one exception was raised. Will report only the first one and log others.
[B#360]  io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[B#360]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[B#360]  	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
[B#360]  	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
[B#360]  	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
[B#360]  	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210)
[B#360]  	at pcl.OpenFM.TileEntity.TileEntityRadio.func_145844_m(TileEntityRadio.java:334)
[B#360]  	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
[B#360]  	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533)
[B#360]  	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
[B#360]  	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)
[B#360]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
[B#360]  	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[B#360]  	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[B#360]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[B#360]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[B#360]  Caused by: java.lang.NullPointerException
[B#360]  	at cpw.mods.fml.common.network.ByteBufUtils.writeUTF8String(ByteBufUtils.java:132)
[B#360]  	at pcl.OpenFM.network.message.MessageRadioSync.toBytes(MessageRadioSync.java:58)
[B#360]  	at pcl.OpenFM.network.MessageRadioBase.toBytes(MessageRadioBase.java:48)
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:11)
[B#360]  	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:7)
[B#360]  	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51)
[B#360]  	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
[B#360]  	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
[B#360]  	... 18 more
[B#360]  
```
and then everything crashes (if I open Radio and hit play) and I have to restart minecraft
